name: Cron Job

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 * * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Install dependencies
        run: uv sync

      - name: Install Playwright browsers
        run: uv run playwright install --with-deps

      - name: Run script
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: uv run python main.py
